name: DevOps Testing Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest --maxfail=1
